### ISSUE TITLE
Spacing issues

### ISSUE THREAD

**Issue by jonohrt** [timcharper/evil-surround#76]
With the following:
`first second third not`
placing the cursor at the beginning of the line and entering
`ys3w{`
I get
`{ first second third  }not`
When I do the same thing in Vim I get
`{ first second third } not`
which is what I expected.

**Comment by wbolster** [comment]
this package does not automagically insert extra spaces that are not part of the pair definition, e.g. `{` expands to ` {` and `} ` (with leading and trailing spaces).

fwiw, you can use `ys3e{` to achieve what you want, since `3e` selects until the end of the word, instead of the beginning of the next word like `3w` would do.

**Comment by ninrod** [comment]
@jonohrt, what wbolster said.
